import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';
import { sassPlugin } from 'esbuild-sass-plugin';


const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

/** @type {esbuild.SameShape<esbuild.BuildOptions, esbuild.BuildOptions>} */
const options = {
	banner: {
		js: banner,
	},
	entryPoints: ['src/plugin.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		'@jest/*',
		'jest',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
    minify: prod
}

/** @type {esbuild.SameShape<esbuild.BuildOptions, esbuild.BuildOptions>} */
const styleOptions = {
    banner: {
        css: banner
    },
	entryPoints: ['src/styles.scss'],
	bundle: true,
	outfile: 'styles.css',
	logLevel: "info",
	minify: prod,
	plugins: [sassPlugin()],
};

if (prod) {
	await esbuild.build(options);
    await esbuild.build(styleOptions);
	process.exit(0);
} else {
    const context = await esbuild.context(options);
	const styleContext = await esbuild.context(styleOptions);
	await Promise.all([
		context.watch(),
		styleContext.watch()
	]);
}
