name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["plugin-bug"]
assignees:
- KrazyManJ
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: textarea
  id: bug-description
  attributes:
    label: Describe a bug
    description: Write a short description of a bug
  validations:
    required: true

- type: textarea
  id: steps-to-reproduce
  attributes:
  label: Steps to reproduce
  description: What are the steps to reproduce
  placeholder: |
    1. Go to '...'
    2. Click on '....'
    3. Scroll down to '....'
    4. See error
  validations:
    required: true

- type: dropdown
  id: os
  attributes:
    label: Operating system
    description: What operating system are you using (can confirm this bug on)
    multiple: true
    options:
      - Windows
      - MacOS
      - Linux
    validations:
        required: true

- type: textarea
  id: additional-context
  attributes:
    label: Additional context
    description: Tell me aditional context to a problem (every detail would help me)
  validations:
    required: false